SDK integration
browserstack/browserstack-examples-appium-testng pull request #2
Opened 2022-12-28 16:35 UTC by hrishi1096

2022-12-28 16:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/BrowserStackCE/browserstack-examples-appium-testng?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/BrowserStackCE/browserstack-examples-appium-testng?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/BrowserStackCE/browserstack-examples-appium-testng?pullRequest=2) it.</sub>

2022-12-29 12:12 UTC, abhi-singhs commented on src/test/resources/conf/capabilities/browserstack-parallel-devices.yml
> +platforms:
You'll need to add 2-3 devices to this profile.

2022-12-29 12:18 UTC, abhi2810 requested changes
Do we need [LocalSample.apk](https://github.com/BrowserStackCE/browserstack-examples-appium-testng/blob/sdk_review/apps/LocalSample.apk) App?

2022-12-29 13:01 UTC, tschoem commented
> Do we need [LocalSample.apk](https://github.com/BrowserStackCE/browserstack-examples-appium-testng/blob/sdk_review/apps/LocalSample.apk) App?

We've decided to add them even in this repo @abhi2810 : https://github.com/browserstack/testng-appium-app-browserstack/pull/24/files

because it is very unintuitive for customers using the repos without access to the apps...

2022-12-29 13:11 UTC, abhi2810 commented
> > Do we need [LocalSample.apk](https://github.com/BrowserStackCE/browserstack-examples-appium-testng/blob/sdk_review/apps/LocalSample.apk) App?
> 
> We've decided to add them even in this repo @abhi2810 : https://github.com/browserstack/testng-appium-app-browserstack/pull/24/files
> 
> because it is very unintuitive for customers using the repos without access to the apps...

I asked this question because this app is not used anywhere in the repo.

2022-12-29 13:16 UTC, tschoem commented on src/test/resources/conf/capabilities/browserstack-parallel-devices.yml
> +platforms:
Done!

2022-12-29 13:19 UTC, tschoem commented
> I asked this question because this app is not used anywhere in the repo.

Oh maybe it should be referenced in the readme / browserstack-local.yml files ?

2022-12-29 14:09 UTC, abhi2810 commented
> > I asked this question because this app is not used anywhere in the repo.
> 
> Oh maybe it should be referenced in the readme / browserstack-local.yml files ?

The LocalSample app is not relevant to this code repo. The main BrowserStack App has Local testing capabilities and the code is also written accordingly.

2022-12-29 15:32 UTC, tschoem commented
ah ok i'll remove the changes and the app

2022-12-29 16:07 UTC, tschoem commented
Some more notes here:
- the onprem configs don't run locally anymore. I'm not sure if we can change the pom file to fix this
- several of the tests actually fail. It might be worth fixing them for both sdk and regular branch

2023-01-06 11:49 UTC, hrishi1096 commented
LocalSample.apk has been removed already by Thomas.

As for the failing tests, I noticed that they are failing intermittently because the app crashes and this is when I run it with mvn. Strangely enough, when I run the same suite/profile with gradle, they all pass.

2023-01-11 15:03 UTC, hrishi1096 commented
There are some test failures and problems with the on-prem profile as stated in a previous comment but all the changes related to SDK conversion are done and tested.

Merging this PR now and will create a new ticket (and consequently a PR) to fix the other problems specifically.
Hope that's okay. @abhi2810 @tschoem

2023-01-11 15:14 UTC, abhi2810 approved these changes

2023-01-11 16:24 UTC, merged